"""initial marketing schema

Revision ID: 0d6491da3ab7
Revises: 
Create Date: 2026-04-27 16:16:40.196696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d6491da3ab7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brands_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_brands_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_brands_name'), ['name'], unique=True)

    op.create_table('press_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('outlet', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('beat', sa.String(length=255), nullable=True),
    sa.Column('scope', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('twitter_handle', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('press_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_press_contacts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_press_contacts_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_press_contacts_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_press_contacts_scope'), ['scope'], unique=False)

    op.create_table('system_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_configs_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_configs_key'), ['key'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active_user', sa.Boolean(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('brand_api_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.Column('credential_type', sa.String(length=50), nullable=False),
    sa.Column('credentials', sa.Text(), nullable=False),
    sa.Column('access_token', sa.String(length=1024), nullable=True),
    sa.Column('refresh_token', sa.String(length=1024), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('service_settings', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'service', name='unique_brand_service_credential')
    )
    with op.batch_alter_table('brand_api_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brand_api_credentials_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brand_api_credentials_service'), ['service'], unique=False)

    op.create_table('brand_email_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('api_key', sa.String(length=1024), nullable=False),
    sa.Column('api_token', sa.String(length=1024), nullable=True),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_user', sa.String(length=255), nullable=True),
    sa.Column('smtp_password', sa.String(length=1024), nullable=True),
    sa.Column('from_email', sa.String(length=255), nullable=False),
    sa.Column('from_name', sa.String(length=255), nullable=True),
    sa.Column('reply_to_email', sa.String(length=255), nullable=True),
    sa.Column('reply_to_name', sa.String(length=255), nullable=True),
    sa.Column('contact_lists', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('max_send_per_day', sa.Integer(), nullable=True),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('verification_error', sa.Text(), nullable=True),
    sa.Column('emails_sent_today', sa.Integer(), nullable=True),
    sa.Column('last_send_timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'provider', name='unique_brand_provider')
    )
    with op.batch_alter_table('brand_email_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brand_email_configs_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brand_email_configs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_brand_email_configs_provider'), ['provider'], unique=False)

    op.create_table('brand_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('daily_email_limit', sa.Integer(), nullable=True),
    sa.Column('enable_email_sending', sa.Boolean(), nullable=True),
    sa.Column('enable_ai_generation', sa.Boolean(), nullable=True),
    sa.Column('enable_social_posting', sa.Boolean(), nullable=True),
    sa.Column('auto_subscribe_new_contacts', sa.Boolean(), nullable=True),
    sa.Column('auto_unsubscribe_invalid', sa.Boolean(), nullable=True),
    sa.Column('default_campaign_type', sa.String(length=50), nullable=True),
    sa.Column('default_send_time', sa.String(length=5), nullable=True),
    sa.Column('default_send_day_of_week', sa.Integer(), nullable=True),
    sa.Column('enable_analytics_tracking', sa.Boolean(), nullable=True),
    sa.Column('enable_utm_parameters', sa.Boolean(), nullable=True),
    sa.Column('advanced_settings', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brand_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brand_settings_brand_id'), ['brand_id'], unique=True)

    op.create_table('brand_themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('secondary_color', sa.String(length=7), nullable=True),
    sa.Column('accent_color', sa.String(length=7), nullable=True),
    sa.Column('nav_gradient_from', sa.String(length=7), nullable=True),
    sa.Column('nav_gradient_to', sa.String(length=7), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('favicon_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brand_themes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brand_themes_brand_id'), ['brand_id'], unique=True)

    op.create_table('content_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('template_name', sa.String(length=255), nullable=False),
    sa.Column('template_slug', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('platform', sa.Enum('REDDIT', 'HACKER_NEWS', 'INDIE_HACKERS', 'LINKEDIN', 'DEVTO', 'TWITTER', 'YOUTUBE', 'TIKTOK', 'EMAIL', 'WEBSITE', 'PRODUCT_HUNT', name='platformtype'), nullable=False),
    sa.Column('task_type', sa.Enum('SOCIAL_POST', 'ARTICLE', 'VIDEO', 'EMAIL', 'PAID_AD', 'PRESS_RELEASE', 'PODCAST', 'WEBINAR', 'EVENT', 'CUSTOM', name='tasktype'), nullable=False),
    sa.Column('title_template', sa.String(length=500), nullable=True),
    sa.Column('body_template', sa.Text(), nullable=True),
    sa.Column('cta', sa.String(length=255), nullable=True),
    sa.Column('hashtags', sa.String(length=500), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('performance_metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_name'], ['brands.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketing_calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('campaign_name', sa.String(length=255), nullable=False),
    sa.Column('campaign_slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goal', sa.String(length=255), nullable=True),
    sa.Column('target_metric', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_name'], ['brands.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('press_releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('headline', sa.String(length=500), nullable=True),
    sa.Column('subheadline', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('boilerplate', sa.Text(), nullable=True),
    sa.Column('contact_info', sa.Text(), nullable=True),
    sa.Column('news_event', sa.Text(), nullable=True),
    sa.Column('target_scope', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('distributed_at', sa.DateTime(), nullable=True),
    sa.Column('distribution_targets', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('press_releases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_press_releases_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_press_releases_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_press_releases_status'), ['status'], unique=False)

    op.create_table('scheduled_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('schedule_label', sa.String(length=100), nullable=True),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=True),
    sa.Column('fail_count', sa.Integer(), nullable=True),
    sa.Column('last_result', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_tasks_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_tasks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_tasks_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_tasks_task_type'), ['task_type'], unique=False)

    op.create_table('user_brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'brand_id', name='unique_user_brand')
    )
    with op.batch_alter_table('user_brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_brands_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_brands_user_id'), ['user_id'], unique=False)

    op.create_table('api_credential_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('email_config_id', sa.Integer(), nullable=True),
    sa.Column('api_credential_id', sa.Integer(), nullable=True),
    sa.Column('system_config_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('action_by', sa.String(length=255), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['api_credential_id'], ['brand_api_credentials.id'], ),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['email_config_id'], ['brand_email_configs.id'], ),
    sa.ForeignKeyConstraint(['system_config_id'], ['system_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_credential_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_credential_logs_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_credential_logs_created_at'), ['created_at'], unique=False)

    op.create_table('marketing_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('task_slug', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.Enum('SOCIAL_POST', 'ARTICLE', 'VIDEO', 'EMAIL', 'PAID_AD', 'PRESS_RELEASE', 'PODCAST', 'WEBINAR', 'EVENT', 'CUSTOM', name='tasktype'), nullable=True),
    sa.Column('platform', sa.Enum('REDDIT', 'HACKER_NEWS', 'INDIE_HACKERS', 'LINKEDIN', 'DEVTO', 'TWITTER', 'YOUTUBE', 'TIKTOK', 'EMAIL', 'WEBSITE', 'PRODUCT_HUNT', name='platformtype'), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('scheduled_time', sa.Time(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='taskstatus'), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='taskpriority'), nullable=True),
    sa.Column('is_automated', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('executed_by', sa.String(length=255), nullable=True),
    sa.Column('execution_log', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('performance_metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_name'], ['brands.name'], ),
    sa.ForeignKeyConstraint(['calendar_id'], ['marketing_calendar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketing_weekly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('calendar_id', sa.Integer(), nullable=True),
    sa.Column('week_start', sa.DateTime(), nullable=False),
    sa.Column('week_end', sa.DateTime(), nullable=False),
    sa.Column('posts_published', sa.Integer(), nullable=True),
    sa.Column('total_reach', sa.Integer(), nullable=True),
    sa.Column('total_engagement', sa.Integer(), nullable=True),
    sa.Column('total_clicks', sa.Integer(), nullable=True),
    sa.Column('total_conversions', sa.Integer(), nullable=True),
    sa.Column('signups', sa.Integer(), nullable=True),
    sa.Column('platform_metrics', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('top_performing_post', sa.String(length=255), nullable=True),
    sa.Column('insights', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_name'], ['brands.name'], ),
    sa.ForeignKeyConstraint(['calendar_id'], ['marketing_calendar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marketing_weekly')
    op.drop_table('marketing_task')
    with op.batch_alter_table('api_credential_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_credential_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_api_credential_logs_brand_id'))

    op.drop_table('api_credential_logs')
    with op.batch_alter_table('user_brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_brands_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_brands_brand_id'))

    op.drop_table('user_brands')
    with op.batch_alter_table('scheduled_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_tasks_task_type'))
        batch_op.drop_index(batch_op.f('ix_scheduled_tasks_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_scheduled_tasks_created_at'))
        batch_op.drop_index(batch_op.f('ix_scheduled_tasks_brand_id'))

    op.drop_table('scheduled_tasks')
    with op.batch_alter_table('press_releases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_press_releases_status'))
        batch_op.drop_index(batch_op.f('ix_press_releases_created_at'))
        batch_op.drop_index(batch_op.f('ix_press_releases_brand_id'))

    op.drop_table('press_releases')
    op.drop_table('marketing_calendar')
    op.drop_table('content_template')
    with op.batch_alter_table('brand_themes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brand_themes_brand_id'))

    op.drop_table('brand_themes')
    with op.batch_alter_table('brand_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brand_settings_brand_id'))

    op.drop_table('brand_settings')
    with op.batch_alter_table('brand_email_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brand_email_configs_provider'))
        batch_op.drop_index(batch_op.f('ix_brand_email_configs_created_at'))
        batch_op.drop_index(batch_op.f('ix_brand_email_configs_brand_id'))

    op.drop_table('brand_email_configs')
    with op.batch_alter_table('brand_api_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brand_api_credentials_service'))
        batch_op.drop_index(batch_op.f('ix_brand_api_credentials_brand_id'))

    op.drop_table('brand_api_credentials')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_configs_key'))
        batch_op.drop_index(batch_op.f('ix_system_configs_category'))

    op.drop_table('system_configs')
    with op.batch_alter_table('press_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_press_contacts_scope'))
        batch_op.drop_index(batch_op.f('ix_press_contacts_is_active'))
        batch_op.drop_index(batch_op.f('ix_press_contacts_email'))
        batch_op.drop_index(batch_op.f('ix_press_contacts_created_at'))

    op.drop_table('press_contacts')
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brands_name'))
        batch_op.drop_index(batch_op.f('ix_brands_is_active'))
        batch_op.drop_index(batch_op.f('ix_brands_created_at'))

    op.drop_table('brands')
    # ### end Alembic commands ###
