#!/usr/bin/env python3
"""
Multi-Brand Daily Analytics Email System
========================================

Sends comprehensive daily analytics reports for all brands using the
proven foundry system as a template. Integrates with the real analytics
system to provide actual performance data.

Based on foundry/scripts/analytics_reporter.py and startup_outreach.py
"""

import os
import smtplib
import json
from datetime import datetime, timedelta
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from pathlib import Path
from typing import Dict, Any, List
import sys

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from config.brand_loader import get_all_brands, get_brand_details

# Import our real analytics system
from automation.real_analytics_dashboard import get_analytics_for_dashboard

def _load_daily_email_config() -> Dict[str, Dict[str, Any]]:
    """Load brand email configurations from database"""
    config = {}
    brands = get_all_brands(active_only=True)
    
    for brand in brands:
        brand_data = get_brand_details(brand)
        if brand_data:
            config[brand] = {
                'name': brand_data.get('display_name', brand.title()),
                'website': brand_data.get('website_url', f'https://{brand}.io'),
                'team_email': os.getenv(f'{brand.upper()}_TEAM_EMAIL', f'team@{brand}.io'),
                'cc_emails': [os.getenv('ADMIN_EMAIL', 'admin@buildly.io')],
                'notification_subject': f"{brand_data.get('display_name', brand.title())} Daily Analytics Report"
            }
    
    return config

# Brand configurations for daily emails - loaded dynamically
DAILY_EMAIL_CONFIG = _load_daily_email_config()

# SMTP Configuration (using foundry's proven Brevo setup)
SMTP_CONFIG = {
    'service': 'brevo',
    'smtp_server': 'smtp-relay.brevo.com',
    'smtp_port': 587,
    'username': os.getenv('BREVO_SMTP_USER', ''),
    'password': os.getenv('BREVO_SMTP_PASSWORD', ''),
    'from_name': 'Marketing Analytics System',
    'from_email': 'team@buildly.io'
}

class DailyAnalyticsEmailer:
    """Sends daily analytics emails for all brands"""
    
    def __init__(self):
        self.project_root = project_root
        self.reports_dir = self.project_root / 'data' / 'daily_reports'
        self.reports_dir.mkdir(parents=True, exist_ok=True)
    
    def generate_daily_email_content(self, brand_key: str, analytics_data: Dict) -> Dict[str, str]:
        """Generate email content based on analytics data"""
        brand_config = DAILY_EMAIL_CONFIG.get(brand_key, {})
        brand_name = brand_config.get('name', brand_key)
        website = analytics_data.get('brand', {}).get('website', '')
        
        # Extract key metrics
        website_data = analytics_data.get('website', {})
        email_data = analytics_data.get('email', {})
        performance_data = analytics_data.get('performance', {})
        
        sessions = website_data.get('sessions', 0)
        users = website_data.get('users', 0)
        pageviews = website_data.get('pageviews', 0)
        bounce_rate = website_data.get('bounce_rate', 0)
        
        emails_sent = email_data.get('sent', 0)
        open_rate = email_data.get('open_rate', 0)
        click_rate = email_data.get('click_rate', 0)
        
        performance_score = performance_data.get('score', 0)
        performance_rating = performance_data.get('rating', 'unknown')
        recommendations = performance_data.get('recommendations', [])
        
        # Generate subject
        subject = f"{brand_name} Daily Analytics Report - {datetime.now().strftime('%B %d, %Y')}"
        
        # Generate text body
        text_body = f"""
{brand_name} Daily Analytics Report
{datetime.now().strftime('%A, %B %d, %Y')}

📊 WEBSITE PERFORMANCE
======================
• Sessions: {sessions:,}
• Unique Users: {users:,} 
• Page Views: {pageviews:,}
• Bounce Rate: {bounce_rate:.1%}

📧 EMAIL CAMPAIGNS
==================
• Emails Sent: {emails_sent}
• Open Rate: {open_rate:.1f}%
• Click Rate: {click_rate:.1f}%

⭐ PERFORMANCE SCORE
====================
Overall Score: {performance_score:.1f}/10 ({performance_rating.title()})

🎯 RECOMMENDATIONS
==================
"""
        
        if recommendations:
            for i, rec in enumerate(recommendations[:3], 1):
                text_body += f"{i}. {rec}\n"
        else:
            text_body += "• Performance is good! Continue current strategies.\n"
        
        text_body += f"""

🌐 Dashboard: http://localhost:5003
📈 Website: {website}

---
This report was automatically generated by the Marketing Analytics System.
"""
        
        # Generate HTML body
        html_body = f"""
<html>
<head>
    <style>
        body {{ font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; }}
        .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; text-align: center; }}
        .metric-card {{ background: #f8f9fa; border: 1px solid #dee2e6; border-radius: 8px; padding: 15px; margin: 10px 0; }}
        .metric-title {{ font-weight: bold; color: #495057; margin-bottom: 10px; }}
        .metric-value {{ font-size: 24px; font-weight: bold; color: #007bff; }}
        .performance-score {{ font-size: 28px; font-weight: bold; }}
        .excellent {{ color: #28a745; }}
        .good {{ color: #17a2b8; }}
        .needs_improvement {{ color: #ffc107; }}
        .recommendations {{ background: #e7f3ff; border-left: 4px solid #007bff; padding: 15px; }}
        .footer {{ background: #f8f9fa; padding: 15px; text-align: center; color: #6c757d; font-size: 12px; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>📊 {brand_name} Daily Analytics</h1>
        <p>{datetime.now().strftime('%A, %B %d, %Y')}</p>
    </div>
    
    <div style="padding: 20px;">
        <h2>🌐 Website Performance</h2>
        
        <div class="metric-card">
            <div class="metric-title">Sessions</div>
            <div class="metric-value">{sessions:,}</div>
        </div>
        
        <div class="metric-card">
            <div class="metric-title">Unique Users</div>
            <div class="metric-value">{users:,}</div>
        </div>
        
        <div class="metric-card">
            <div class="metric-title">Page Views</div>
            <div class="metric-value">{pageviews:,}</div>
        </div>
        
        <div class="metric-card">
            <div class="metric-title">Bounce Rate</div>
            <div class="metric-value">{bounce_rate:.1%}</div>
        </div>
        
        <h2>📧 Email Campaigns</h2>
        
        <div class="metric-card">
            <div class="metric-title">Emails Sent</div>
            <div class="metric-value">{emails_sent}</div>
        </div>
        
        <div class="metric-card">
            <div class="metric-title">Open Rate</div>
            <div class="metric-value">{open_rate:.1f}%</div>
        </div>
        
        <div class="metric-card">
            <div class="metric-title">Click Rate</div>
            <div class="metric-value">{click_rate:.1f}%</div>
        </div>
        
        <h2>⭐ Performance Score</h2>
        <div class="metric-card">
            <div class="performance-score {performance_rating}">{performance_score:.1f}/10</div>
            <div>Rating: {performance_rating.replace('_', ' ').title()}</div>
        </div>
        
        <h2>🎯 Recommendations</h2>
        <div class="recommendations">
"""
        
        if recommendations:
            for i, rec in enumerate(recommendations[:3], 1):
                html_body += f"<p><strong>{i}.</strong> {rec}</p>"
        else:
            html_body += "<p><strong>✅</strong> Performance is good! Continue current strategies.</p>"
        
        html_body += f"""
        </div>
        
        <div style="text-align: center; margin: 30px 0;">
            <a href="http://localhost:5003" style="background: #007bff; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px;">
                📊 View Dashboard
            </a>
            <a href="{website}" style="background: #28a745; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; margin-left: 10px;">
                🌐 Visit Website
            </a>
        </div>
    </div>
    
    <div class="footer">
        This report was automatically generated by the Marketing Analytics System.<br>
        Generated on {datetime.now().strftime('%Y-%m-%d at %H:%M:%S')}
    </div>
</body>
</html>
"""
        
        return {
            'subject': subject,
            'text_body': text_body,
            'html_body': html_body
        }
    
    def send_daily_report_email(self, brand_key: str, email_content: Dict[str, str], dry_run: bool = False) -> bool:
        """Send daily report email for a specific brand"""
        try:
            brand_config = DAILY_EMAIL_CONFIG.get(brand_key, {})
            team_email = brand_config.get('team_email')
            cc_emails = brand_config.get('cc_emails', [])
            
            if not team_email:
                print(f"❌ No team email configured for {brand_key}")
                return False
            
            if dry_run:
                print(f"🧪 [DRY RUN] Would send daily report to {team_email} (CC: {', '.join(cc_emails)})")
                print(f"   Subject: {email_content['subject']}")
                return True
            
            # Create SMTP connection using proven Brevo config
            server = smtplib.SMTP(SMTP_CONFIG['smtp_server'], SMTP_CONFIG['smtp_port'])
            server.starttls()
            server.login(SMTP_CONFIG['username'], SMTP_CONFIG['password'])
            
            # Create message
            msg = MIMEMultipart('alternative')
            msg['From'] = f"{SMTP_CONFIG['from_name']} <{SMTP_CONFIG['from_email']}>"
            msg['To'] = team_email
            msg['Subject'] = email_content['subject']
            msg['Reply-To'] = SMTP_CONFIG['from_email']
            
            # Add CC emails
            if cc_emails:
                msg['Cc'] = ', '.join(cc_emails)
            
            # Add both text and HTML versions
            text_part = MIMEText(email_content['text_body'], 'plain')
            html_part = MIMEText(email_content['html_body'], 'html')
            
            msg.attach(text_part)
            msg.attach(html_part)
            
            # Send to all recipients
            all_recipients = [team_email] + cc_emails
            server.send_message(msg, to_addrs=all_recipients)
            server.quit()
            
            print(f"✅ Daily report sent to {team_email} (CC: {', '.join(cc_emails)})")
            return True
            
        except Exception as e:
            print(f"❌ Failed to send daily report for {brand_key}: {e}")
            return False
    
    def send_all_daily_reports(self, dry_run: bool = False) -> Dict[str, bool]:
        """Send daily reports for all brands"""
        results = {}
        
        print(f"🚀 Sending daily analytics reports for all brands...")
        if dry_run:
            print("🧪 DRY RUN MODE - No emails will be sent")
        
        for brand_key in DAILY_EMAIL_CONFIG.keys():
            try:
                print(f"\n📊 Processing {brand_key.title()}...")
                
                # Get analytics data for this brand
                analytics_data = get_analytics_for_dashboard(brand_key)
                
                # Generate email content
                email_content = self.generate_daily_email_content(brand_key, analytics_data)
                
                # Send email
                success = self.send_daily_report_email(brand_key, email_content, dry_run)
                results[brand_key] = success
                
            except Exception as e:
                print(f"❌ Error processing {brand_key}: {e}")
                results[brand_key] = False
        
        # Summary
        successful = sum(results.values())
        total = len(results)
        
        print(f"\n📈 Daily Reports Summary:")
        print(f"   ✅ Successful: {successful}")
        print(f"   ❌ Failed: {total - successful}")
        print(f"   📊 Total: {total}")
        
        return results
    
    def send_multi_brand_summary(self, dry_run: bool = False) -> bool:
        """Send a single summary email with all brands"""
        try:
            # Get summary data for all brands
            summary_data = get_analytics_for_dashboard()
            
            # Generate cross-brand summary email
            subject = f"Marketing Analytics Summary - {datetime.now().strftime('%B %d, %Y')}"
            
            total_sessions = summary_data['summary']['total_sessions']
            total_users = summary_data['summary']['total_users'] 
            total_emails = summary_data['summary']['total_emails']
            
            text_body = f"""
Marketing Analytics Summary
{datetime.now().strftime('%A, %B %d, %Y')}

📊 OVERALL PERFORMANCE
======================
• Total Sessions: {total_sessions:,}
• Total Users: {total_users:,}
• Total Emails Sent: {total_emails:,}
• Brands Tracked: {len(summary_data['brands'])}

🏢 BRAND BREAKDOWN
==================
"""
            
            html_body = f"""
<html>
<head>
    <style>
        body {{ font-family: Arial, sans-serif; max-width: 700px; margin: 0 auto; }}
        .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; text-align: center; }}
        .summary-card {{ background: #f8f9fa; border: 1px solid #dee2e6; border-radius: 8px; padding: 15px; margin: 10px 0; }}
        .brand-row {{ display: flex; justify-content: space-between; padding: 10px; border-bottom: 1px solid #eee; }}
        .metric {{ font-size: 18px; font-weight: bold; color: #007bff; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>📊 Marketing Analytics Summary</h1>
        <p>{datetime.now().strftime('%A, %B %d, %Y')}</p>
    </div>
    
    <div style="padding: 20px;">
        <div class="summary-card">
            <h3>Overall Performance</h3>
            <div class="brand-row">
                <span>Total Sessions:</span>
                <span class="metric">{total_sessions:,}</span>
            </div>
            <div class="brand-row">
                <span>Total Users:</span>
                <span class="metric">{total_users:,}</span>
            </div>
            <div class="brand-row">
                <span>Total Emails:</span>
                <span class="metric">{total_emails:,}</span>
            </div>
        </div>
        
        <h3>🏢 Brand Performance</h3>
"""
            
            for brand in summary_data['brands']:
                brand_name = brand['name']
                sessions = brand['sessions']
                rating = brand['performance_rating']
                
                text_body += f"• {brand_name}: {sessions:,} sessions ({rating})\n"
                
                html_body += f"""
        <div class="brand-row">
            <span>{brand_name}</span>
            <span>{sessions:,} sessions ({rating})</span>
        </div>
"""
            
            text_body += f"""

🌐 Dashboard: http://localhost:5003

---
This summary was automatically generated by the Marketing Analytics System.
"""
            
            html_body += f"""
        
        <div style="text-align: center; margin: 30px 0;">
            <a href="http://localhost:5003" style="background: #007bff; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px;">
                📊 View Full Dashboard
            </a>
        </div>
    </div>
</body>
</html>
"""
            
            email_content = {
                'subject': subject,
                'text_body': text_body, 
                'html_body': html_body
            }
            
            # Send to main analytics email
            if dry_run:
                print("🧪 [DRY RUN] Would send multi-brand summary to greg@buildly.io")
                return True
            
            # Send using SMTP
            server = smtplib.SMTP(SMTP_CONFIG['smtp_server'], SMTP_CONFIG['smtp_port'])
            server.starttls()
            server.login(SMTP_CONFIG['username'], SMTP_CONFIG['password'])
            
            msg = MIMEMultipart('alternative')
            msg['From'] = f"{SMTP_CONFIG['from_name']} <{SMTP_CONFIG['from_email']}>"
            msg['To'] = 'greg@buildly.io'
            msg['Subject'] = email_content['subject']
            
            text_part = MIMEText(email_content['text_body'], 'plain')
            html_part = MIMEText(email_content['html_body'], 'html')
            
            msg.attach(text_part)
            msg.attach(html_part)
            
            server.send_message(msg, to_addrs=['greg@buildly.io'])
            server.quit()
            
            print("✅ Multi-brand summary sent to greg@buildly.io")
            return True
            
        except Exception as e:
            print(f"❌ Failed to send multi-brand summary: {e}")
            return False

def main():
    """Test the daily analytics email system"""
    import argparse
    
    parser = argparse.ArgumentParser(description='Send daily analytics reports')
    parser.add_argument('--dry-run', action='store_true', help='Test run without sending emails')
    parser.add_argument('--brand', type=str, help='Send report for specific brand only')
    parser.add_argument('--summary-only', action='store_true', help='Send only multi-brand summary')
    
    args = parser.parse_args()
    
    emailer = DailyAnalyticsEmailer()
    
    if args.summary_only:
        # Send only the multi-brand summary
        emailer.send_multi_brand_summary(dry_run=args.dry_run)
    elif args.brand:
        # Send report for specific brand
        analytics_data = get_analytics_for_dashboard(args.brand)
        email_content = emailer.generate_daily_email_content(args.brand, analytics_data)
        emailer.send_daily_report_email(args.brand, email_content, dry_run=args.dry_run)
    else:
        # Send all brand reports + summary
        emailer.send_all_daily_reports(dry_run=args.dry_run)
        print("\n📧 Sending multi-brand summary...")
        emailer.send_multi_brand_summary(dry_run=args.dry_run)

if __name__ == '__main__':
    main()